### ISSUE TITLE
some preview contents questions.

### ISSUE THREAD

**Issue by MinYn** [Garulf/pyFlowLauncher#4]
![스크린샷 2024-01-31 225916](https://github.com/Garulf/pyFlowLauncher/assets/7910274/2970ae90-d6d8-4339-a8e0-07db412368e7)
- I would like to show preview content in this space, but is it currently possible to implement this?

**Comment by Garulf** [comment]
This is possible, I just haven't added the proper field to `Result` due to the way it is coded in Flow Launcher. 

I'll add it today if I get a moment.

**Comment by Garulf** [comment]
Added to v0.8.1:

https://github.com/Garulf/pyFlowLauncher/blob/e15b1b7f9c2f51447785e800c6dbc4b2f8e3351b/pyflowlauncher/result.py#L31-L36

**Comment by MinYn** [comment]
@Garulf Thank you for adding it to the development list for me, I will change this issue to resolved if I can apply it as soon as possible. thank you

**Comment by Garulf** [comment]
> @Garulf Thank you for adding it to the development list for me, I will change this issue to resolved if I can apply it as soon as possible. thank you

No problem, it was on the todo list to implement, I just needed to familiarize myself with the data structure again.

You should be able to use it with the latest release.

**Comment by Garulf** [comment]
Closing this issue. Let me know if this needs further discussion.
